### ISSUE TITLE
Save model

### ISSUE THREAD

**Issue by wallneradam** [KristianHolsheimer/keras-gym#13]
Thanks for your great library. I learned a lot from it...
My question: Is there an easy way to save and restore my trained models?

**Comment by KristianHolsheimer** [comment]
Thanks. Yes, I should've added that functionality already.

I won't be implementing it any time soon, though. The reason is that I've ported the **keras-gym** package from Tensorflow to JAX. But as I haven't written this new package in my spare time, I'll have to open-source it through the official Microsoft channels. I'll definitely let you know when that's available.

For the time being, you could save your model weights by calling `save_weights()` on the underlying keras models, e.g.
```python
q.train_model.save_weights('/path/to/weights.train.h5')
q.predict_model.save_weights('/path/to/weights.predict.h5')
```
and then load them again later by using
```python
q.train_model.load_weights('/path/to/weights.train.h5')
q.predict_model.load_weights('/path/to/weights.predict.h5')
```
See also: https://keras.io/models/about-keras-models/
